version: 2

name: QUIZ_BOT_BETA
database: USER$KOYO_NASU
schema: PUBLIC
query_warehouse: TEAM_B_WH

install:
  commands:
    - ["npm", "ci", "--include=dev"]

build:
  commands:
    - ["npm", "run", "build"]
    - ["cp", "-r", ".next/static", ".next/standalone/.next/static"]
    - ["cp", "-r", "public", ".next/standalone/public"]
    - ["rm", "-rf", "node_modules"]

run:
  command: ["node", ".next/standalone/server.js"]

ignore:
  - node_modules
  - .env*
  - __pycache__
  - "*.pyc"
  - .next
  - .git
  - snowflake.log
