-- QZ_BASE: Apple Gift Card + .tsv.gz カテゴリ汚染を除外したビュー
-- 集計テーブル・問題作成はすべてこのビューから取る
USE WAREHOUSE TEAM_B_WH;

CREATE OR REPLACE VIEW TEAM_B_DB.DEVELOPMENT.QZ_BASE AS
SELECT *
FROM TEAM_B_DB.DEVELOPMENT.MART_RAKUTEN_PURCHASES_RFM
WHERE ITEM_NAME NOT ILIKE '%apple gift%'
  AND ITEM_NAME NOT ILIKE '% gift card%'
  AND COALESCE(CATEGORY_LEVEL_4, '') NOT LIKE '%.tsv.gz%';
