-- 集計テーブル 5 本（QZ_BASE ベース）
-- 注文 = COUNT(DISTINCT USER_ID_HASH || '|' || PURCHASED_AT)
USE WAREHOUSE TEAM_B_WH;

-- 1. カテゴリ別
CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_CAT AS
SELECT
    CATEGORY_LEVEL_1,
    SUM(TOTAL_PRICE)                                          AS SALES,
    COUNT(*)                                                   AS ORDERS,
    COUNT(DISTINCT USER_ID_HASH)                               AS CUSTOMERS,
    ROUND(SUM(TOTAL_PRICE) / NULLIF(COUNT(*), 0))             AS AOV,
    ROUND(100.0 * SUM(CASE WHEN GENDER_NAME = '女性' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1)  AS FEMALE_SHARE,
    ROUND(AVG(AGE), 1)                                         AS AVG_AGE
FROM TEAM_B_DB.DEVELOPMENT.QZ_BASE
WHERE CATEGORY_LEVEL_1 IS NOT NULL
GROUP BY CATEGORY_LEVEL_1
ORDER BY SALES DESC;

-- 2. 都道府県別
CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_STATE AS
SELECT
    STATE_NAME,
    SUM(TOTAL_PRICE)                              AS SALES,
    COUNT(*)                                       AS ORDERS,
    COUNT(DISTINCT USER_ID_HASH)                   AS CUSTOMERS,
    ROUND(SUM(TOTAL_PRICE) / NULLIF(COUNT(*), 0)) AS AOV
FROM TEAM_B_DB.DEVELOPMENT.QZ_BASE
WHERE STATE_NAME IS NOT NULL AND STATE_NAME != '不明'
GROUP BY STATE_NAME
ORDER BY SALES DESC;

-- 3. 月×カテゴリ
CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_MONTH_CAT AS
SELECT
    PURCHASE_MONTH,
    CATEGORY_LEVEL_1,
    SUM(TOTAL_PRICE) AS SALES,
    COUNT(*)          AS ORDERS
FROM TEAM_B_DB.DEVELOPMENT.QZ_BASE
WHERE CATEGORY_LEVEL_1 IS NOT NULL
GROUP BY PURCHASE_MONTH, CATEGORY_LEVEL_1
ORDER BY PURCHASE_MONTH, CATEGORY_LEVEL_1;

-- 4. 週×カテゴリ
CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_WEEK_CAT AS
SELECT
    DATE_TRUNC('WEEK', PURCHASE_DATE) AS WEEK_START,
    CATEGORY_LEVEL_1,
    SUM(TOTAL_PRICE)                  AS SALES,
    COUNT(*)                           AS ORDERS
FROM TEAM_B_DB.DEVELOPMENT.QZ_BASE
WHERE CATEGORY_LEVEL_1 IS NOT NULL
GROUP BY WEEK_START, CATEGORY_LEVEL_1
ORDER BY WEEK_START, CATEGORY_LEVEL_1;

-- 5. RFM セグメント×カテゴリ（セグメント内売上構成比）
CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_SEG_CAT AS
WITH base AS (
    SELECT
        RFM_SEGMENT,
        CATEGORY_LEVEL_1,
        SUM(TOTAL_PRICE) AS SALES
    FROM TEAM_B_DB.DEVELOPMENT.QZ_BASE
    WHERE CATEGORY_LEVEL_1 IS NOT NULL
      AND RFM_SEGMENT IS NOT NULL
    GROUP BY RFM_SEGMENT, CATEGORY_LEVEL_1
)
SELECT
    RFM_SEGMENT,
    CATEGORY_LEVEL_1,
    SALES,
    ROUND(100.0 * SALES / SUM(SALES) OVER (PARTITION BY RFM_SEGMENT), 2) AS SHARE
FROM base
ORDER BY RFM_SEGMENT, SALES DESC;
