-- QZ_WEATHER_TOKYO: NOAA 東京観測所（JA000047662）の日次天気
-- 期間: 2023/4/1 〜 2024/3/31
-- 検算: 361 日、降水量合計 1,424.5mm（東京平年 ~1,600mm）
USE WAREHOUSE TEAM_B_WH;

CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_WEATHER_TOKYO AS
SELECT DATE,
       MAX(IFF(VARIABLE='precipitation', VALUE, NULL)) AS PRECIP_MM,
       MAX(IFF(VARIABLE='maximum_temperature', VALUE, NULL)) AS TMAX_C
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.NOAA_WEATHER_METRICS_TIMESERIES
WHERE NOAA_WEATHER_STATION_ID = 'JA000047662'
  AND VARIABLE IN ('precipitation','maximum_temperature')
  AND DATE BETWEEN '2023-04-01' AND '2024-03-31'
GROUP BY DATE;

-- 検算
SELECT COUNT(*) AS DAYS, SUM(PRECIP_MM) AS TOTAL_PRECIP_MM
FROM TEAM_B_DB.DEVELOPMENT.QZ_WEATHER_TOKYO;
