-- QZ_AGG_WEATHER: 東京都顧客 × 天気結合
-- IS_RAINY = 降水 1mm 以上, IS_WEEKDAY = 月〜金 (DAYOFWEEKISO)
-- 'すべて' 行の ORDERS = COUNT(DISTINCT USER_ID_HASH || '|' || PURCHASED_AT)（二重計上防止）
-- Apple Gift Card + .tsv.gz 除外済み
USE WAREHOUSE TEAM_B_WH;

CREATE OR REPLACE TABLE TEAM_B_DB.DEVELOPMENT.QZ_AGG_WEATHER AS
WITH purchases AS (
    SELECT *
    FROM TEAM_B_DB.DEVELOPMENT.MART_RAKUTEN_PURCHASES_RFM
    WHERE STATE_NAME = '東京都'
      AND ITEM_NAME NOT ILIKE '%apple gift%'
      AND ITEM_NAME NOT ILIKE '% gift card%'
      AND COALESCE(CATEGORY_LEVEL_4, '') NOT LIKE '%.tsv.gz%'
),
cat_daily AS (
    SELECT
        p.PURCHASE_DATE AS DATE,
        w.PRECIP_MM >= 1 AS IS_RAINY,
        DAYOFWEEKISO(p.PURCHASE_DATE) BETWEEN 1 AND 5 AS IS_WEEKDAY,
        p.CATEGORY_LEVEL_1,
        SUM(p.TOTAL_PRICE) AS SALES,
        COUNT(*) AS ORDERS
    FROM purchases p
    INNER JOIN TEAM_B_DB.DEVELOPMENT.QZ_WEATHER_TOKYO w ON p.PURCHASE_DATE = w.DATE
    GROUP BY p.PURCHASE_DATE, IS_RAINY, IS_WEEKDAY, p.CATEGORY_LEVEL_1
),
total_daily AS (
    SELECT
        p.PURCHASE_DATE AS DATE,
        w.PRECIP_MM >= 1 AS IS_RAINY,
        DAYOFWEEKISO(p.PURCHASE_DATE) BETWEEN 1 AND 5 AS IS_WEEKDAY,
        'すべて' AS CATEGORY_LEVEL_1,
        SUM(p.TOTAL_PRICE) AS SALES,
        COUNT(DISTINCT p.USER_ID_HASH || '|' || p.PURCHASED_AT) AS ORDERS
    FROM purchases p
    INNER JOIN TEAM_B_DB.DEVELOPMENT.QZ_WEATHER_TOKYO w ON p.PURCHASE_DATE = w.DATE
    GROUP BY p.PURCHASE_DATE, IS_RAINY, IS_WEEKDAY
)
SELECT * FROM cat_daily
UNION ALL
SELECT * FROM total_daily
ORDER BY DATE, CATEGORY_LEVEL_1;

-- 検算: 平日の雨 vs 非雨の中央値
SELECT IS_RAINY, MEDIAN(ORDERS) AS MEDIAN_ORDERS, COUNT(*) AS DAYS
FROM TEAM_B_DB.DEVELOPMENT.QZ_AGG_WEATHER
WHERE IS_WEEKDAY = TRUE AND CATEGORY_LEVEL_1 = 'すべて'
GROUP BY IS_RAINY;
